### PR TITLE
Ecs drive monitoring in cloudwatch

### PR DESCRIPTION
**Pull request by lukaspour**
This is an addition to our ECS cluster to create a script which would keep track of inner ECS docker drive. It creates three metrics and bind it with alert which triggers at 80%. I noticed we use cloudwatch-agent but I haven't found any documentation which would help me create something similar without using external script.

### CODE REVIEW

**Comment by lukaspour** [comment]
Thanks for the review.

- I'll prepare alert as terraform resource, it seems as a good idea, I guess I have put it into the script to be sure it is deployed. I will make some option which if true create the alert and deploy the script.
- I'll generate name of alert with random number postfix to be sure not to collide with anything else
- This script ask for `docker info` values directly. This can help in case the `/dev/xvdcz` is not used by docker. In case of ECS I guess it doesn't matter.

**Comment by itsdalmo** [comment]
> I'll prepare alert as terraform resource, it seems as a good idea, I guess I have put it into the script to be sure it is deployed. I will make some option which if true create the alert and deploy the script.
I'll generate name of alert with random number postfix to be sure not to collide with anything else

What I actually meant is that it should be created in terraform, but not in this module. If users want to have a Cloudwatch rule they can just define it in their terraform code.

> This script ask for docker info values directly. This can help in case the /dev/xvdcz is not used by docker. In case of ECS I guess it doesn't matter.

Still, I'm not convinced that it is a general enough use case that it should be part of this module. As per the discussion in this PR: https://github.com/TeliaSoneraNorge/telia-terraform-modules/pull/83, docker volume usage is not really something you need to monitor/worry about if you don't write logs to the containers. It is a volume that is supposed to only exist for layers and images, and running containers, and is garbage collected by docker itself.

With that in mind, I'd suggest one of two things:
- A: Expose `user_data` so it can be configured to whatever the user wants. But this means we are no longer opinionated.
- B: Make it possible to add additional [logging drivers](https://docs.docker.com/config/containers/logging/configure/) besides `awslogs`, and also set up the cloudwatch agent to report the `disk_usage_percent` for the root drive of the instance (in case logs are being written to the filesystem).

**Comment by lukaspour** [comment]
I customized the `user_data` to be defined by user if needed. Also I've changed the permissions to be custom as well. If user would like to use module `user_data` and change `logging drivers`, he can use custom variable `logging_drivers`.

**Comment by itsdalmo** [comment]
Makes perfect sense @lukaspour 👍

**Comment by itsdalmo** [comment]
Please remove the WIP tag before merging.

**Pull request merged**
